[HOPSWORKS-2578] Create logs dir under data dir
logicalclocks/kafka-cookbook pull request #59
Opened 2021-07-09 09:41 UTC by kouzant

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578

2021-07-09 13:43 UTC, tkakantousis approved these changes

2021-07-25 22:11 UTC, SirOibaf requested changes

2021-07-25 22:11 UTC, SirOibaf commented on recipes/install.rb
> +    rm -rf #{node['kkafka']['log_dir']}
Would be great to have the `_deprecated` move here as well. Just in case we need to recover stuff.

2021-07-25 22:13 UTC, SirOibaf approved these changes

2021-08-02 10:50 UTC, merged